AWSTemplateFormatVersion: '2010-09-09'
Description: Sysdig for Cloud - AWS Edition
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Sysdig Settings
        Parameters:
          - SysdigSecureEndpoint
          - SysdigSecureAPIToken
      - Label:
          default: Modules to Deploy
        Parameters:
          - CloudBenchDeploy
          - CloudConnectorDeploy
          - ECRImageScanningDeploy
          - ECSImageScanningDeploy
      - Label:
          default: Existing Infrastructure
        Parameters:
          - ExistentECSCluster
          - ExistentECSClusterVPC
          - ExistentECSClusterPrivateSubnets
    ParameterLabels:
      SysdigSecureEndpoint:
        default: Sysdig Secure Endpoint
      SysdigSecureAPIToken:
        default: Sysdig Secure API Token
      CloudBenchDeploy:
        default: Do you want to deploy Cloud Security Posture Management / Compliance?
      CloudConnectorDeploy:
        default: Do you want to deploy Real-Time Threat Investigation based on CloudTrail?
      ECRImageScanningDeploy:
        default: Do you want to deploy ECR Image Registry Scanning?
      ECSImageScanningDeploy:
        default: Do you want to deploy Fargate Image Scanning?
      ExistentECSCluster:
        default: ECS Cluster Name
      ExistentECSClusterVPC:
        default: VPC Id
      ExistentECSClusterPrivateSubnets:
        default: Private subnet Id's
  QuickStartDocumentation:
    EntrypointName: Quickstart for Sysdig CloudVision stack
Parameters:
  CloudBenchDeploy:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
  CloudConnectorDeploy:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
  ECRImageScanningDeploy:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
  ECSImageScanningDeploy:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
  ExistentECSCluster:
    Type: String
    Default: ''
    Description: Leave it blank to let us to deploy the infrastructure required for
      running Sysdig for Cloud
  ExistentECSClusterVPC:
    Type: String
    Default: ''
    Description: Leave it blank to let us to deploy the infrastructure required for
      running Sysdig for Cloud
  ExistentECSClusterPrivateSubnets:
    Type: List<String>
    Default: ''
    Description: Leave it blank to let us to deploy the infrastructure required for
      running Sysdig for Cloud
  SysdigSecureAPIToken:
    Type: String
    NoEcho: true
  SysdigSecureEndpoint:
    Type: String
    Default: https://secure.sysdig.com
Resources:
  CloudVisionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-cloudvision-ci.s3-eu-west-1.amazonaws.com/master/entry-point.yaml
      Parameters:
        SysdigSecureEndpoint: !Ref SysdigSecureEndpoint
        SysdigSecureAPIToken: !Ref SysdigSecureAPIToken
        CloudBenchDeploy: !Ref CloudBenchDeploy
        CloudConnectorDeploy: !Ref CloudConnectorDeploy
        ECRImageScanningDeploy: !Ref ECRImageScanningDeploy
        ECSImageScanningDeploy: !Ref ECSImageScanningDeploy
        ExistentECSCluster: !Ref ExistentECSCluster
        ExistentECSClusterVPC: !Ref ExistentECSClusterVPC
        ExistentECSClusterPrivateSubnets: !Ref ExistentECSClusterPrivateSubnets
